alias k='kubectl'
alias kd='kubectl describe'
alias kdd='kubectl describe deployment'
alias kdp='kubectl describe pod'
alias kg='kubectl get'
alias kgi='kubectl get ingress'
alias kgp='kubectl get pods -o wide'
alias kgs='kubectl get services -o wide'
